version: '3.5'

services:
  api:
    image: api
    container_name: "api"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - SERVER_MODE=${SERVER_MODE}

volumes:
  database-repository: # database named volume